apiVersion: v2
appVersion: 0.5.0-SNAPSHOT # Should be maintained automatically by a pipeline
name: thirdeye
description: One Stop Shop For Anomaly Detection. Built on Apache Pinot
version: 0.1.0
keywords:
- olap
- analytics
- pinot
- anomaly detection
- rootcause analysis
home: https://github.com/apache/incubator-pinot
sources:
- https://github.com/apache/incubator-pinot
maintainers:
- name: Alexander Pucher
  email: alex@cortexdata.io
- name: Suvodeep Pyne
  email: pyne.suvodeep@gmail.com
dependencies:
- name: mysql
  version: 1.6.6
  repository: https://charts.helm.sh/stable
