frameworks:
    ###########################################################################
    # Default RCA framework, all inclusive
    ###########################################################################
    default:
        #######################################################################
        # Metrics
        #######################################################################
        - outputName: METRIC_FROM_METRIC_DATASET
          inputNames: [INPUT]
          className: com.linkedin.thirdeye.rootcause.impl.MetricDatasetPipeline

        - outputName: METRIC_FROM_METRIC
          inputNames: [INPUT]
          className: com.linkedin.thirdeye.rootcause.impl.EntityMappingPipeline
          properties:
              mappingType: METRIC_TO_METRIC

        - outputName: METRIC_TOPK
          inputNames: [INPUT, METRIC_FROM_METRIC_DATASET, METRIC_FROM_METRIC]
          className: com.linkedin.thirdeye.rootcause.impl.TopKPipeline
          properties:
              class: com.linkedin.thirdeye.rootcause.impl.MetricEntity
              k: 20

        #######################################################################
        # Dimensions
        #######################################################################
        - outputName: DIMENSION_FROM_METRIC
          inputNames: [INPUT, METRIC_TOPK]
          className: com.linkedin.thirdeye.rootcause.impl.DimensionAnalysisPipeline
          properties:
              parallelism: 5

        - outputName: DIMENSION_STANDARDIZED
          inputNames: [DIMENSION_FROM_METRIC]
          className: com.linkedin.thirdeye.rootcause.impl.EntityMappingPipeline
          properties:
              mappingType: DIMENSION_TO_DIMENSION
              isRewriter: true
              matchPrefix: true

        - outputName: DIMENSION_TOPK
          inputNames: [INPUT, DIMENSION_STANDARDIZED]
          className: com.linkedin.thirdeye.rootcause.impl.TopKPipeline
          properties:
              class: com.linkedin.thirdeye.rootcause.impl.DimensionEntity
              k: 50

        #######################################################################
        # Services
        #######################################################################
        - outputName: SERVICE_FROM_METRIC
          inputNames: [INPUT, METRIC_TOPK]
          className: com.linkedin.thirdeye.rootcause.impl.EntityMappingPipeline
          properties:
              mappingType: METRIC_TO_SERVICE

        - outputName: SERVICE_TOPK
          inputNames: [INPUT, SERVICE_FROM_METRIC]
          className: com.linkedin.thirdeye.rootcause.impl.TopKPipeline
          properties:
              class: com.linkedin.thirdeye.rootcause.impl.ServiceEntity
              k: 10

        #######################################################################
        # Events
        #######################################################################
        - outputName: EVENT_HOLIDAY
          inputNames: [INPUT, DIMENSION_TOPK]
          className: com.linkedin.thirdeye.rootcause.impl.ThirdEyeEventsPipeline

        - outputName: EVENT_ANOMALY
          inputNames: [INPUT, METRIC_TOPK]
          className: com.linkedin.thirdeye.rootcause.impl.AnomalyEventsPipeline

        - outputName: EVENT_TOPK
          inputNames: [INPUT, EVENT_HOLIDAY, EVENT_ANOMALY]
          className: com.linkedin.thirdeye.rootcause.impl.TopKPipeline
          properties:
              class: com.linkedin.thirdeye.rootcause.impl.EventEntity
              k: 20

        #######################################################################
        # Results
        #######################################################################
        - outputName: OUTPUT
          inputNames: [EVENT_TOPK, METRIC_TOPK, DIMENSION_TOPK, SERVICE_TOPK]
          className: com.linkedin.thirdeye.rootcause.impl.TopKPipeline
          properties:
              k: 50

    relatedMetrics:
        #######################################################################
        # Metrics
        #######################################################################
        - outputName: METRIC_FROM_METRIC
          inputNames: [INPUT]
          className: com.linkedin.thirdeye.rootcause.impl.EntityMappingPipeline
          properties:
              mappingType: METRIC_TO_METRIC

        - outputName: METRIC_TOPK
          inputNames: [METRIC_FROM_METRIC]
          className: com.linkedin.thirdeye.rootcause.impl.TopKPipeline
          properties:
              class: com.linkedin.thirdeye.rootcause.impl.MetricEntity
              k: 10

        - outputName: OUTPUT
          inputNames: [INPUT, METRIC_TOPK]
          className: com.linkedin.thirdeye.rootcause.impl.MetricCorrelationRankingPipeline
          properties:
              targetInput: INPUT

