language: java
os: linux
dist: trusty

before_install:
  - sudo apt-get update && sudo apt-get install -y --no-install-recommends gdb
  - mkdir -p ~/bin && curl -sSL -o ~/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x ~/bin/jq
  - export PATH=$PATH:~/bin
  - jq --version
  - curl -sSL -o ~/bin/install-jdk.sh https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh && chmod +x ~/bin/install-jdk.sh
  - source ./.travis/.travis_set_deploy_build_opts.sh

before_cache:
  - rm -rf $HOME/.m2/repository/org/apache/pinot

cache:
  directories:
    - $HOME/.m2
  yarn: true

addons:
  firefox: latest

install:
  - ./.travis/.travis_install.sh

#branches:
#  only:
#    - master

stages:
  - test
  - name: deploy
#    if: branch = master

jobs:
  include:
#    - name: "Integration Tests - OracleJDK 8"
#      jdk: oraclejdk8
#      script:
#        - ./.travis/.travis_test.sh
#      env:
#        - RUN_INTEGRATION_TESTS=true
#    - name: "Unit Tests - OracleJDK 8"
#      jdk: oraclejdk8
#      script:
#        - ./.travis/.travis_test.sh
#      env:
#        - RUN_INTEGRATION_TESTS=false
#    - name: "QuickStart - Java 8 & OpenJDK 14-15"
#      jdk: oraclejdk8
#      script:
#        - ./.travis/.travis_quickstart.sh
#        - jdk_switcher use openjdk8
#        - ./.travis/.travis_install.sh
#        - ./.travis/.travis_quickstart.sh
#        - ./.travis/.travis_quickstart_openjdk.sh 14
#        - ./.travis/.travis_quickstart_openjdk.sh 15
#    - name: "QuickStart - OpenJDK 10-13"
#      jdk: openjdk10
#      script:
#        - java -version
#        - ./.travis/.travis_quickstart.sh
#        - ./.travis/.travis_quickstart_openjdk.sh 11
#        - ./.travis/.travis_quickstart_openjdk.sh 12
#        - ./.travis/.travis_quickstart_openjdk.sh 13
    - stage: deploy
      script:
        - travis_wait 40 ./.travis/.travis_nightly_build.sh
        - travis_wait 60 ./.travis/.travis_te_nightly_build.sh

env:
  global:
    - secure: R3NdobUAThkk6BBzXapek6PiuWHWa1ldnJBvXpk2TAi7Lua/Ctgg8EHCSve7+MK4SU3XFJSi1th32+VSy0K/ARfdVcxiVh6EJSL/Nw0LRQSvGk7VjO382SsWCFoJuZBBqjy9DfBgRLdoqEPfulIBC0XBxjJ+4xedRptkZo7+TAAvtB8Y32EA5ve+Z4cdJipLF1tviL5q2rVbkNXucYUYO2XIv5HOzF2Xy3Hw6lsNrHpbes2CLEkoMiLOQ30zfbXZT/5Xd6OhQNmoZJ9gKziT1opiN2AJMPv269K8FFJZTrDZX74/thq9wmeF4X4f3wPA7EbTupooj0i9LPzb8Xev1QKAsxBtHyRm9NGYOXM06c2yKiGsDtT4HZYQGk4m8/89moe3oGnEwvw/JLu5RvLIZzFE2cBhHrcxRAJgHLIr80+kebNg/YstNlDL+rmP0b9NRrGIVw5OO2BT27ZBgsMFmjnujQtCUJiJ5zqyMxygaYmgZha6xcbhFUPyf4DJ3T46etyFovg2EJnhM7HL9ECZHloQZFhEKs88sZXqvt6HKsA77xyL7ONMrwcPtdDVbFUkN/B1R7LLOf6Wq5vK/Y2EB18oXhKF0ngdahT8HKSMTXjuYf5MPybxhf4fdY6stFmIVkd9b633iZDMu+Aj8E1c8BApyDikCmYK2BI3grH49E0=
    - secure: Hj71ADg7ZgQpn8PUbEjaz1RrjkPfPCpGksp+WDjE6jf+oDvl55ILQhPgNcxIy81UcxS3Gmx6UWteVGkNV4Fi59TJIQ8KPbQ9RU2FFVXcxHH2TmkOvdNezwkJIFUw0TNMCbRAXgDj7ov75BM6lLi271GfqPVg9pB504Bc43WohnV6lDo/y93Z/xWbuFk5uJ+cogAJme3pvYHxBNlNzwIYnNAAqrEb+YKsRuux3qWLTlm1guT78g3C9wl/WCelTo1A3hGd12FqFWmowcoQlAyhbnFJ7u7qwfSNTSGCFLYbrUGooXqTZg2B+2QZORT2b5b0P9SXgB2a/UJxXmxkUzbmPGdUJipmQCEemlxwkPCqMW0YSscTDHU5WjSxqy4Cvwa8y+DEpLu06WxAPwjBje53025PvLjsMEfNJ0wsQbm9jkrH0alzICemXyyV5uGBCmuiMv5WqZ70WEpy7xlPlk5aFTwWQRpYJ5mhQCnHCgQfiX1/reEo6Vi5DzsW6A0Qtr5UERwMpQwYd47ErbobyuJY4Bcfz/TXqfaCY2+ER9kWil87dBTDpH5K8X68FHxIwNx2OxGVwlc3JhpMXJ2uFDDeXvsPlQA2kQWgZnC03qXSZX5YmTOjHoNREGtgEsgDZS1vM5M3KZkOG0+76MWL5p/zgHfVjzS3T15W4PVWlki/WZ0=
    - secure: VfBYdV1EKmIBQlJj6yYUmucDU33HOm2dZLGcWC91QFVQx3FCOFzhSwTcby/gFM/9q/OzudKIRyTLV3iCtM1j1dEQA+oHLq6T1uV8DsOXnY908oShK1eil53aa3Ki4tYyMhR8WiXqVCoXglSB/Eakl6X2FnBfj0au+jvYLgPJE9IgY8hOvmp9ZdX5yFCbgcU2lmmJb7TZSnarrdtDBPuMG4dmRoqcUMxslvIZskOs38NVfkR4fj3gPGt2yZcauEKrqiiBF1nLGLfkigrifdHTW9fkIQtQmLwKrZx7+Mxz0GHAIrkGfoauQKfJy6fdFjyumtxWPxHKG1LlkmjrXEOustCefRy9S2bMkemgbCFT4jXsgHBCfmmV4BFADwvxcWSI6U9iSqeHfQMRgyvrJ36PaVi66UjVs+nPKPjMeHNcO32edB71/BKINEOgd38J1f4qTaUfnNexAf/lAT+rxl9PMfAuttDM5QGwdDfQa/6+hRnGJaPyHiAALFqLpgabJ3oRUsQA7D8DHb+Rk8vstsVEeuB0h/WrqepzKyPz38FqxbODAsLuhPv1hunecT/u7Vj2PZnLSoBF85cklEfYnqofu3eFJr2GyoY0Wa70PRw+lpGsrbBkiQoGkpehv7WEECUB3RZEighTHcBauAyR4dg8hmt29EXFOUXHrTrRaFZszp8=
    - secure: Vp4Bv3B9RsImeo4zSiaiJMg4NvzgYRo/90ykozpoRjGQR1Ix7wBSsJvtFsf9iEVRBO5zrpT8GbdaV/Ed+UGi9XZVOnQEHS89pbscRAz2aIBfBlS0DCDrZAvxYP6XvwlJd1wz0zt1b87+dUeWyoEJWpZrzb3Z3knGTaNLnPYpW3HuG6BOv5bwo/n0ptY05IabsqPRi1yEiHdT/eSef6wLEhZuXtPXdUr7WMhjNNmIY6bwIH6ld2gUY3/1lVlz4ryd4+fPiPgaDc9ffWbn9JK8oHX+EEabkGXehkWbm/7dkBV+y0W+sV8Cw2+adhWX86FuS1J+2GoTcqpkB+Do36nAMccY9yKulpB6Kb0OInNSrZHLMtJl6p6Txm9VkihGTvGAlWEX8OhGFx/AEPf6cuVMpD4uzF7HS/L2fvlBYZbilUptaMzr/LDjfO0xdJF4wbtkBX0w2x7ISp2lIj2aVcKSERqisrTxaQhtF6g2c39cVN+vC8TB1IplofL1qWTimQL6CHFoJ62cPDtCXrMEpW1y/dTMx4oh+0FKt2vqohLEB+AZ1+nRpUrmVjtmYIPxhmPBSGYFVyl3yZgStbsQfJWHLoW1huZcF0+PxOJODVeBj7Lop8WeGFHbdqUX1fBDsiAy3n9KGFXin3l/RkW3Phr7uI1+BeW8oRxxgywPscgmn2w=
    - secure: Mg2mAcQRycTMKKU5g9xFvpe1DISMPEtGQgtCrnxpGMTLGUVaT1nUDa18OUgGuENjGy/slYeQZXQTkO/pQtxrPJcueXbG6ZMBa6Z0OizncX2G+FVtpuUGhy0LdSQFjAD5LAJy4DF5fQl4hlZ8Ucp0Er1o+j28UoETQ413jFj+hkevxpd+jIZ+VsLumedI3ChaRs9nZQG0cCv/RtHZPDQGuEJ6U4e4p/wTA1zCIVuqxS94pKq2IY3QTpQrBXdeIwaRkyhgZDhG43PSPqNGmSQU5WnLJRMzaQYc2+LowKhpjba+WouJ/PuyLiIUwOu2r7e+HGiXh9Wak0xM27m5g6kG1dqYEhVCIgTUBM2IJempcDJqZsw00m9t1Zv6PuYlMQDJPRoLVdpy7IIsR5OmZQbMegFw4ciNzjCPVV5xiYuBGg3VscDTLYosHLcYv3HjqV+d+vIQS39RjzWTKaMleBH5m8kYSeGZerQ+3fJURQtYGwBTT5qCmlGQZWvLgyi9Et5soex88Wj9ywEeCK6o1bzZ7kaKzgmBHHatpDeclW24z3tcHF/xSzX5y30l7pAX2EYC/hmjEBp3yRRNBUuJUmR3sktOIXP6OwFIUxwRjf/UVnhKIzyOYLB2oFu1PavczpnB87VWY1vQLvIHjpJi5HG9+wNn2hkoD/TwFwevNhHYZS8=
