language: java

env:
  - RUN_INTEGRATION_TESTS=true
  - RUN_INTEGRATION_TESTS=false

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
  yarn: true


dist: precise
sudo: false

addons:
  firefox: latest

install:
  - ./.travis_install.sh

script:
  - ./.travis_test.sh

branches:
  only:
    - master