language: java

env:
  - RUN_INTEGRATION_TESTS=true
  - RUN_INTEGRATION_TESTS=false

jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

matrix:
  exclude:
    - jdk: openjdk7
      env: RUN_INTEGRATION_TESTS=false
    - jdk: oraclejdk8
      env: RUN_INTEGRATION_TESTS=false

install:
  - ./.travis_install.sh

script:
  - ./.travis_test.sh

branches:
  only:
    - master
