language: java
sudo: false
dist: trusty

env:
  global:
    - JOBS=1
  matrix:
    - RUN_INTEGRATION_TESTS=true
    - RUN_INTEGRATION_TESTS=false

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
  yarn: true

addons:
  firefox: latest

install:
  - ./.travis_install.sh

script:
  - ./.travis_test.sh

branches:
  only:
    - master
