language: java

env:
  - RUN_INTEGRATION_TESTS=true
  - RUN_INTEGRATION_TESTS=false

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

dist: precise
sudo: false

install:
  - ./.travis_install.sh

script:
  - ./.travis_test.sh

branches:
  only:
    - master
