logging:
  type: external
server:
  type: default
  rootPath: '/api/*'
  applicationContextPath: /
  adminContextPath: /admin
  applicationConnectors:
    - type: http
      port: 1867
  adminConnectors:
    - type: http
      port: 1868
  requestLog:
    type: external
alert: true
autoload: true
classifier: false
holidayEventsLoader: false
mockEventsLoader: true
monitor: false
pinotProxy: false
scheduler: true
worker: true
detectionPipeline: true
detectionAlert: true
dashboardHost: "http://localhost:1426"
id: 0
alerterConfiguration:
  smtpConfiguration:
    smtpHost: "localhost"
    smtpPort: 25
#  jiraConfiguration:
#    jiraUser: <REPLACE_ME>
#    jiraPassword: <REPLACE_ME>
#    jiraUrl: <REPLACE_ME>
#    jiraDefaultProject: <REPLACE_ME>
#    jiraIssueTypeId: 19
failureFromAddress: "thirdeye@localhost"
failureToAddress: "thirdeye@localhost"
phantomJsPath: "/usr/local/bin/jstf"
swagger:
  resourcePackage: "org.apache.pinot.thirdeye.dashboard.resources,org.apache.pinot.thirdeye.dashboard.resources.v2,org.apache.pinot.thirdeye.anomaly.onboard"
holidayEventsLoaderConfiguration:
  calendars:
       - "en.australian#holiday@group.v.calendar.google.com"
       - "en.austrian#holiday@group.v.calendar.google.com"
       - "en.brazilian#holiday@group.v.calendar.google.com"
       - "en.canadian#holiday@group.v.calendar.google.com"
       - "en.china#holiday@group.v.calendar.google.com"
       - "en.christian#holiday@group.v.calendar.google.com"
       - "en.danish#holiday@group.v.calendar.google.com"
       - "en.dutch#holiday@group.v.calendar.google.com"
       - "en.finnish#holiday@group.v.calendar.google.com"
       - "en.french#holiday@group.v.calendar.google.com"
       - "en.german#holiday@group.v.calendar.google.com"
       - "en.greek#holiday@group.v.calendar.google.com"
       - "en.hong_kong#holiday@group.v.calendar.google.com"
       - "en.indian#holiday@group.v.calendar.google.com"
       - "en.indonesian#holiday@group.v.calendar.google.com"
       - "en.irish#holiday@group.v.calendar.google.com"
       - "en.islamic#holiday@group.v.calendar.google.com"
       - "en.italian#holiday@group.v.calendar.google.com"
       - "en.japanese#holiday@group.v.calendar.google.com"
       - "en.jewish#holiday@group.v.calendar.google.com"
       - "en.malaysia#holiday@group.v.calendar.google.com"
       - "en.mexican#holiday@group.v.calendar.google.com"
       - "en.new_zealand#holiday@group.v.calendar.google.com"
       - "en.norwegian#holiday@group.v.calendar.google.com"
       - "en.philippines#holiday@group.v.calendar.google.com"
       - "en.polish#holiday@group.v.calendar.google.com"
       - "en.portuguese#holiday@group.v.calendar.google.com"
       - "en.russian#holiday@group.v.calendar.google.com"
       - "en.singapore#holiday@group.v.calendar.google.com"
       - "en.sa#holiday@group.v.calendar.google.com"
       - "en.south_korea#holiday@group.v.calendar.google.com"
       - "en.spain#holiday@group.v.calendar.google.com"
       - "en.swedish#holiday@group.v.calendar.google.com"
       - "en.taiwan#holiday@group.v.calendar.google.com"
       - "en.thai#holiday@group.v.calendar.google.com"
       - "en.uk#holiday@group.v.calendar.google.com"
       - "en.usa#holiday@group.v.calendar.google.com"
       - "en.vietnamese#holiday@group.v.calendar.google.com"
  holidayLoadRange: 2592000000
  runFrequency: 7
mockEventsLoaderConfiguration:
  generators:
    - type: HOLIDAY
      arrivalType: exponential
      arrivalMean: 86400000
      durationType: fixed
      durationMean: 86400000
      seed: 0
      namePrefixes: [First, Second, Third, Last, Funky, Happy, Sad, Glorious, Jolly, Unity, Pinot's]
      nameSuffixes: [day, day, days, celebration, rememberance, occurrence, moment]
    - type: INFORMED
      arrivalType: exponential
      arrivalMean: 43200000
      durationType: exponential
      durationMean: 3600000
      seed: 1
      namePrefixes: [Login, Web, Search, Catalog, Integration, Network, Backup, Ingress, Proxy, Failure, Pinot, ThirdEye]
      nameSuffixes: [backend, frontend, v1.1, v1.2, v1.3, v2.0, v3, v4, v5, storage, topic, container, database]
    - type: CM
      arrivalType: exponential
      arrivalMean: 21600000
      durationType: fixed
      durationMean: 1800000
      seed: 2
      namePrefixes: [Database, Web, Search, Catalog, Integration, Network, Backup, Ingress, Proxy, Failure, Pinot, ThirdEye]
    - type: CUSTOM
      arrivalType: exponential
      arrivalMean: 432000000
      durationType: exponential
      durationMean: 86400000
      seed: 3
      namePrefixes: [Marketing, Onboarding, Vaction, Outreach, InDay]
      nameSuffixes: [integration, campaign, meeting]
    - type: LIX
      arrivalType: exponential
      arrivalMean: 259200000
      durationType: exponential
      durationMean: 604800000
      seed: 4
      namePrefixes: [System, Model, Campaign, Welcome, Pinot, ThirdEye]
      nameSuffixes: [tuning, bugfix, rollout, test]
