rules:
# Pinot Controller
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controller.controller(\\w+)\"><>(\\w+)"
  name: "pinot_controller_$1_$2"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controller.helix\\.(\\w+)\"><>(\\w+)"
  name: "pinot_controller_helix_$1_$2"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controller.helixZookeeperReconnects\"><>(\\w+)"
  name: "pinot_controller_helix_ZookeeperReconnects_$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controller.idealstateZnodeSize.(\\w+)_(\\w+)\"><>(\\w+)"
  name: "pinot_controller_idealstateZnodeSize_$3"
  labels:
    table: "$1"
    tableType: "$2"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controller.numberOfReplicas.(\\w+)_(\\w+)\"><>(\\w+)"
  name: "pinot_controller_numberOfReplicas_$3"
  labels:
    table: "$1"
    tableType: "$2"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controller.percentOfReplicas.(\\w+)_(\\w+)\"><>(\\w+)"
  name: "pinot_controller_percentOfReplicas_$3"
  labels:
    table: "$1"
    tableType: "$2"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controller.percentSegmentsAvailable.(\\w+)_(\\w+)\"><>(\\w+)"
  name: "pinot_controller_percentSegmentsAvailable_$3"
  labels:
    table: "$1"
    tableType: "$2"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controller.segmentCount.(\\w+)_(\\w+)\"><>(\\w+)"
  name: "pinot_controller_segmentCount_$3"
  labels:
    table: "$1"
    tableType: "$2"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controller.segmentsInErrorState.(\\w+)_(\\w+)\"><>(\\w+)"
  name: "pinot_controller_segmentsInErrorState_$3"
  labels:
    table: "$1"
    tableType: "$2"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controller.numberSegmentUploadTimeoutExceeded\"><>(\\w+)"
  name: "pinot_controller_numberSegmentUploadTimeoutExceeded_$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controller.numberTimesScheduleTasksCalled\"><>(\\w+)"
  name: "pinot_controller_numberTimesScheduleTasksCalled_$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controller.periodicTaskNumTablesProcessed.(\\w+)\"><>(\\w+)"
  name: "pinot_controller_periodicTaskNumTablesProcessed_$1_$2"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controller.pinotControllerLeader\"><>(\\w+)"
  name: "pinot_controller_pinotControllerLeader_$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controller.pinotControllerPartitionLeader.(\\w+)\"><>(\\w+)"
  name: "pinot_controller_partitionLeader_$1_$2"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controller.realtimeTableCount\"><>(\\w+)"
  name: "pinot_controller_realtimeTableCount_$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ValidationMetrics\", name=\"pinot.controller.(\\w+)\\.(\\w+)\"><>(\\w+)"
  name: "pinot_controller_validateion_$2_$3"
  labels:
    table: "$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controller.cronSchedulerJobScheduled.(\\w+)\\.(\\w+)\"><>(\\w+)"
  name: "pinot_controller_cronSchedulerJobScheduled_$3"
  labels:
    table: "$1"
    taskType: "$2"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controller.(\\w+)\\.(\\w+).cronSchedulerTriggered\"><>(\\w+)"
  name: "pinot_controller_cronSchedulerTriggered_$3"
  labels:
    table: "$1"
    taskType: "$2"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controller.(\\w+)\\.(\\w+).cronSchedulerJobExecutionTimeMs\"><>(\\w+)"
  name: "pinot_controller_cronSchedulerJobExecutionTimeMs_$3"
  labels:
    table: "$1"
    taskType: "$2"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ControllerMetrics\", name=\"pinot.controller.taskStatus.(\\w+)\\.(\\w+)\"><>(\\w+)"
  name: "pinot_controller_taskStatus_$3"
  labels:
    taskType: "$1"
    status: "$2"
# Pinot Broker
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+).authorization\"><>(\\w+)"
  name: "pinot_broker_authorization_$2"
  labels:
    table: "$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)\\.documentsScanned\"><>(\\w+)"
  name: "pinot_broker_documentsScanned_$2"
  labels:
    table: "$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)\\.entriesScannedInFilter\"><>(\\w+)"
  name: "pinot_broker_entriesScannedInFilter_$2"
  labels:
    table: "$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)\\.entriesScannedPostFilter\"><>(\\w+)"
  name: "pinot_broker_entriesScannedPostFilter_$2"
  labels:
    table: "$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)\\.freshnessLagMs\"><>(\\w+)"
  name: "pinot_broker_freshnessLagMs_$2"
  labels:
    table: "$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)\\.queries\"><>(\\w+)"
  name: "pinot_broker_queries_$2"
  labels:
    table: "$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)\\.queryExecution\"><>(\\w+)"
  name: "pinot_broker_queryExecution_$2"
  labels:
    table: "$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)\\.queryRouting\"><>(\\w+)"
  name: "pinot_broker_queryRouting_$2"
  labels:
    table: "$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)\\.reduce\"><>(\\w+)"
  name: "pinot_broker_reduce_$2"
  labels:
    table: "$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)\\.requestCompilation\"><>(\\w+)"
  name: "pinot_broker_requestCompilation_$2"
  labels:
    table: "$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)\\.scatterGather\"><>(\\w+)"
  name: "pinot_broker_scatterGather_$2"
  labels:
    table: "$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)\\.totalServerResponseSize\"><>(\\w+)"
  name: "pinot_broker_totalServerResponseSize_$2"
  labels:
    table: "$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)_(\\w+).groupBySize\"><>(\\w+)"
  name: "pinot_broker_groupBySize_$3"
  labels:
    table: "$1"
    tableType: "$2"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)_(\\w+).noServingHostForSegment\"><>(\\w+)"
  name: "pinot_broker_noServingHostForSegment_$3"
  labels:
    table: "$1"
    tableType: "$2"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.healthcheck(\\w+)\"><>(\\w+)"
  name: "pinot_broker_healthcheck_$1_$2"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.helix.(\\w+)\"><>(\\w+)"
  name: "pinot_broker_helix_$1_$2"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.helixZookeeper(\\w+)\"><>(\\w+)"
  name: "pinot_broker_helix_zookeeper_$1_$2"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.nettyConnection(\\w+)\"><>(\\w+)"
  name: "pinot_broker_nettyConnection_$1_$2"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.clusterChangeCheck\"\"><>(\\w+)"
  name: "pinot_broker_clusterChangeCheck_$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.proactiveClusterChangeCheck\"><>(\\w+)"
  name: "pinot_broker_proactiveClusterChangeCheck_$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.(\\w+)Exceptions\"><>(\\w+)"
  name: "pinot_broker_exceptions_$1_$2"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"BrokerMetrics\", name=\"pinot.broker.routingTableUpdateTime\"><>(\\w+)"
  name: "pinot_broker_routingTableUpdateTime_$1"
# Pinot Server
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.documentCount.(\\w+)_(\\w+)\"><>(\\w+)"
  name: "pinot_server_documentCount_$3"
  labels:
    table: "$1"
    tableType: "$2"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.segmentCount.(\\w+)_(\\w+)\"><>(\\w+)"
  name: "pinot_server_segmentCount_$3"
  labels:
    table: "$1"
    tableType: "$2"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.(\\w+)_(\\w+)\\.(\\w+)\"><>(\\w+)"
  name: "pinot_server_$3_$4"
  labels:
    table: "$1"
    tableType: "$2"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.(\\w+)_(\\w+)\\-(.+)\\-(\\w+).realtimeRowsConsumed\"><>(\\w+)"
  name: "pinot_server_realtimeRowsConsumed_$5"
  labels:
    table: "$1"
    tableType: "$2"
    topic: "$3"
    partition: "$4"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.helix.connected\"><>(\\w+)"
  name: "pinot_server_helix_connected_$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.helixZookeeperReconnects\"><>(\\w+)"
  name: "pinot_server_helix_zookeeperReconnects_$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.highestKafkaOffsetConsumed.(\\w+)_(\\w+)\\-(.+)\\-(\\w+)\"><>(\\w+)"
  name: "pinot_server_highestKafkaOffsetConsumed_$5"
  labels:
    table: "$1"
    tableType: "$2"
    topic: "$3"
    partition: "$4"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.highestStreamOffsetConsumed.(\\w+)_(\\w+)\\-(.+)\\-(\\w+)\"><>(\\w+)"
  name: "pinot_server_highestStreamOffsetConsumed_$5"
  labels:
    table: "$1"
    tableType: "$2"
    topic: "$3"
    partition: "$4"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.lastRealtimeSegment(\\w+)Seconds.(\\w+)_(\\w+)\\-(.+)\\-(\\w+)\"><>(\\w+)"
  name: "pinot_server_lastRealtimeSegment$1Seconds_$6"
  labels:
    table: "$2"
    tableType: "$3"
    topic: "$4"
    partition: "$5"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.llcControllerResponse(\\w+)\"><>(\\w+)"
  name: "pinot_server_llcControllerResponse_$1_$2"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.llcPartitionConsuming.(\\w+)_(\\w+)\\-(.+)\\-(\\w+)\"><>(\\w+)"
  name: "pinot_server_llcPartitionConsuming_$5"
  labels:
    table: "$1"
    tableType: "$2"
    topic: "$3"
    partition: "$4"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.llcSimultaneousSegmentBuilds\"><>(\\w+)"
  name: "pinot_server_llcSimultaneousSegmentBuilds_$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.memory.(\\w+)\"><>(\\w+)"
  name: "pinot_server_memory_$1_$2"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.queries\"><>(\\w+)"
  name: "pinot_server_queries_$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.realtimeConsumptionExceptions\"><>(\\w+)"
  name: "pinot_server_realtime_consumptionExceptions_$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.realtimeOffheapMemoryUsed.(\\w+)\"><>(\\w+)"
  name: "pinot_server_realtime_offheapMemoryUsed_$2"
  labels:
    table: "$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.realtimeOffsetCommits\"><>(\\w+)"
  name: "pinot_server_realtime_offsetCommits_$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.realtimeRowsConsumed\"><>(\\w+)"
  name: "pinot_server_realtime_rowsConsumed_$1"
- pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.(\\w+)Exceptions\"><>(\\w+)"
  name: "pinot_server_realtime_exceptions_$1_$2"
- pattern: "\"org.apache.pinot.transport.netty.NettyTCPServer_(\\w+)_\"<type=\"\", name=\"(\\w+)\"><>(\\w+)"
  name: "pinot_server_netty_tcp_$2_$3"
  labels:
    id: "$1"
# Pinot Minions
- pattern: "\"org.apache.pinot.minion.metrics\"<type=\"MinionMetrics\", name=\"pinot.minion.(\\w+)\"><>(\\w+)"
  name: "pinot_minion_$1_$2"
- pattern: "\"org.apache.pinot.minion.metrics\"<type=\"MinionMetrics\", name=\"pinot.minion.(\\w+).(\\w+)\"><>(\\w+)"
  name: "pinot_minion_$2_$3"
  labels:
    id: "$1"
