
# Please put the mock data source as the first in this configuration.
dataSourceConfigs:
  - className: org.apache.pinot.thirdeye.datasource.mock.MockThirdEyeDataSource
    properties:
      H2:
        db: jdbc:h2:./config/h2db
        user: sa
        password: sa
        datasets:
          - tableName: "H2.H2.total_pageviews"
            timeColumn: "timestamp"
            granularity: "1DAYS"
            timeFormat: "yyyy-MM-dd"
            dimensions: [country, device]
            timezone: "UTC"
            metrics:
              pageviews: "SUM"
            dataFile: "pageviews.csv"

      populateMetaData: true
      lookback: 90
      datasets:
        tracking:
          granularity: "1hour"
          timezone: "America/Los_Angeles"
          dimensions: [country, browser, platform]
          metrics:
            pageViews:
              us:
                chrome:
                  desktop:
                    mean: 100
                    std: 20
                  mobile:
                    mean: 200
                    std: 50
                safari:
                  desktop:
                    mean: 70
                    std: 15
                  mobile:
                    mean: 250
                    std: 40
                firefox:
                  desktop:
                    mean: 30
                    std: 5
                  mobile:
                    mean: 20
                    std: 3
                edge:
                  desktop:
                    mean: 85
                    std: 18
              ca:
                chrome:
                  desktop:
                    mean: 30
                    std: 5
                  mobile:
                    mean: 70
                    std: 8
                safari:
                  desktop:
                    mean: 20
                    std: 3
                  mobile:
                    mean: 60
                    std: 8
                firefox:
                  desktop:
                    mean: 12
                    std: 2
                  mobile:
                    mean: 7
                    std: 1
                edge:
                  desktop:
                    mean: 32
                    std: 10
              mx:
                chrome:
                  desktop:
                    mean: 40
                    std: 6
                  mobile:
                    mean: 80
                    std: 10
                safari:
                  desktop:
                    mean: 20
                    std: 3
                  mobile:
                    mean: 65
                    std: 10
                firefox:
                  desktop:
                    mean: 15
                    std: 3
                  mobile:
                    mean: 12
                    std: 2
                edge:
                  desktop:
                    mean: 32
                    std: 9

            adImpressions:
              us:
                chrome:
                  desktop:
                    mean: 50
                    std: 10
                  mobile:
                    mean: 100
                    std: 25
                safari:
                  desktop:
                    mean: 35
                    std: 7
                  mobile:
                    mean: 125
                    std: 20
                firefox:
                  desktop:
                    mean: 15
                    std: 2
                  mobile:
                    mean: 10
                    std: 1
                edge:
                  desktop:
                    mean: 42
                    std: 9

        business:
          granularity: "1day"
          timezone: "America/Los_Angeles"
          dimensions: [country, browser]
          metrics:
            purchases:
              us:
                chrome:
                  mean: 16
                  std: 2
                safari:
                  mean: 19
                  std: 3
                edge:
                  mean: 4
                  std: 1
              ca:
                chrome:
                  mean: 5
                  std: 1
                safari:
                  mean: 5
                  std: 2
                edge:
                  mean: 1
                  std: 1
              mx:
                chrome:
                  mean: 3
                  std: 1
                safari:
                  mean: 5
                  std: 2
                edge:
                  mean: 2
                  std: 1

            revenue:
              us:
                chrome:
                  mean: 160
                  std: 20
                safari:
                  mean: 190
                  std: 30
                edge:
                  mean: 40
                  std: 10
              ca:
                chrome:
                  mean: 50
                  std: 10
                safari:
                  mean: 50
                  std: 15
                edge:
                  mean: 10
                  std: 2
              mx:
                chrome:
                  mean: 30
                  std: 6
                safari:
                  mean: 50
                  std: 15
                edge:
                  mean: 20
                  std: 3

  - className: org.apache.pinot.thirdeye.datasource.sql.SqlThirdEyeDataSource
    properties:
      H2:
        db: jdbc:h2:./config/h2db
        user: sa
        password: sa
        datasets:
          - tableName: "H2.H2.daily"
            timeColumn: "date"
            granularity: "1DAYS"
            timeFormat: "yyyy-MM-dd"
            timezone: "UTC"
            metrics:
              value: "SUM"
            dataFile: "daily.csv"
          - tableName: "H2.H2.hourly"
            timeColumn: "datetime"
            granularity: "1HOURS"
            timeFormat: "yyyy-MM-dd HH:mm:ss"
            timezone: "UTC"
            metrics:
              value: "SUM"
            dataFile: "hourly.csv"
      PostgreSQL:
        - db:
            utk_test: jdbc:postgresql://127.0.0.1:5432/thirdeye
          user: root
          password: root
      Druid:
        - db:
                #druid_test: jdbc:avatica:remote:url=http://localhost:8082/druid/v2/sql/avatica/
            druid_test: jdbc:avatica:remote:url=https://druid-router.concierge.stage.razorpay.in/druid/v2/sql/avatica/
          user: ""
          password: ""
