#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: thirdeye-config
data:
  persistence.yml: |-
    databaseConfiguration:
      url: jdbc:mysql://{{ .Release.Name }}-mysql/thirdeye
      user: {{ .Values.mysql.mysqlUser }}
      password: {{ .Values.mysql.mysqlPassword }}
      driver: com.mysql.jdbc.Driver
  dashboard.yml: |-
    authConfig:
      authEnabled: false
      authKey: ""
      ldapUrl: ""
      domainSuffix: []
      cacheTTL: 3600
      cookieTTL: 604800
    resourceConfig: []
    rootCause:
      definitionsPath: rca.yml
      parallelism: 5
      formatters:
        - org.apache.pinot.thirdeye.dashboard.resources.v2.rootcause.AnomalyEventFormatter
        - org.apache.pinot.thirdeye.dashboard.resources.v2.rootcause.ThirdEyeEventFormatter
        - org.apache.pinot.thirdeye.dashboard.resources.v2.rootcause.MetricEntityFormatter
        - org.apache.pinot.thirdeye.dashboard.resources.v2.rootcause.DimensionEntityFormatter
        - org.apache.pinot.thirdeye.dashboard.resources.v2.rootcause.ServiceEntityFormatter
        - org.apache.pinot.thirdeye.dashboard.resources.v2.rootcause.DefaultEventEntityFormatter
    dashboardHost: "http://localhost:1426"
    failureFromAddress: thirdeye@localhost
    failureToAddress: user@localhost
    alerterConfiguration:
      smtpConfiguration:
        smtpHost: localhost
        smtpPort: 25
    logging:
      level: INFO
      loggers:
        org.apache.pinot: INFO

    server:
      type: default
      applicationConnectors:
        - type: http
          port: 1426
      adminConnectors:
        - type: http
          port: 1427
      requestLog:
        type: external
    whitelistDatasets: []
    swagger:
      resourcePackage: "org.apache.pinot.thirdeye.dashboard.resources,org.apache.pinot.thirdeye.dashboard.resources.v2,org.apache.pinot.thirdeye.anomaly.onboard,org.apache.pinot.thirdeye.detection,org.apache.pinot.thirdeye.detection.yaml"

  detector.yml: |-
    logging:
      level: INFO
      loggers:
        org.hibernate.engine.internal: WARN
    server:
      type: default
      rootPath: '/api/*'
      applicationContextPath: /
      adminContextPath: /admin
      applicationConnectors:
        - type: http
          port: 1867
      adminConnectors:
        - type: http
          port: 1868
    alert: true
    autoload: true
    # autoOnboardConfiguration:
    #   runFrequency: 10s

    classifier: true
    holidayEventsLoader: true
    monitor: true
    pinotProxy: false
    scheduler: true
    worker: true
    detectionPipeline: true
    detectionAlert: true
    dashboardHost: "http://localhost:1426"
    id: 0
    alerterConfiguration:
      smtpConfiguration:
        smtpHost: "localhost"
        smtpPort: 25
    #  jiraConfiguration:
    #    jiraUser: <REPLACE_ME>
    #    jiraPassword: <REPLACE_ME>
    #    jiraUrl: <REPLACE_ME>
    #    jiraDefaultProject: <REPLACE_ME>
    #    jiraIssueTypeId: 19
    failureFromAddress: "thirdeye@localhost"
    failureToAddress: "thirdeye@localhost"
    phantomJsPath: "/usr/local/bin/jstf"
    swagger:
      resourcePackage: "org.apache.pinot.thirdeye.dashboard.resources,org.apache.pinot.thirdeye.dashboard.resources.v2,org.apache.pinot.thirdeye.anomaly.onboard"
    holidayEventsLoaderConfiguration:
      calendars:
           - "en.australian#holiday@group.v.calendar.google.com"
           - "en.austrian#holiday@group.v.calendar.google.com"
           - "en.brazilian#holiday@group.v.calendar.google.com"
           - "en.canadian#holiday@group.v.calendar.google.com"
           - "en.china#holiday@group.v.calendar.google.com"
           - "en.christian#holiday@group.v.calendar.google.com"
           - "en.danish#holiday@group.v.calendar.google.com"
           - "en.dutch#holiday@group.v.calendar.google.com"
           - "en.finnish#holiday@group.v.calendar.google.com"
           - "en.french#holiday@group.v.calendar.google.com"
           - "en.german#holiday@group.v.calendar.google.com"
           - "en.greek#holiday@group.v.calendar.google.com"
           - "en.hong_kong#holiday@group.v.calendar.google.com"
           - "en.indian#holiday@group.v.calendar.google.com"
           - "en.indonesian#holiday@group.v.calendar.google.com"
           - "en.irish#holiday@group.v.calendar.google.com"
           - "en.islamic#holiday@group.v.calendar.google.com"
           - "en.italian#holiday@group.v.calendar.google.com"
           - "en.japanese#holiday@group.v.calendar.google.com"
           - "en.jewish#holiday@group.v.calendar.google.com"
           - "en.malaysia#holiday@group.v.calendar.google.com"
           - "en.mexican#holiday@group.v.calendar.google.com"
           - "en.new_zealand#holiday@group.v.calendar.google.com"
           - "en.norwegian#holiday@group.v.calendar.google.com"
           - "en.philippines#holiday@group.v.calendar.google.com"
           - "en.polish#holiday@group.v.calendar.google.com"
           - "en.portuguese#holiday@group.v.calendar.google.com"
           - "en.russian#holiday@group.v.calendar.google.com"
           - "en.singapore#holiday@group.v.calendar.google.com"
           - "en.sa#holiday@group.v.calendar.google.com"
           - "en.south_korea#holiday@group.v.calendar.google.com"
           - "en.spain#holiday@group.v.calendar.google.com"
           - "en.swedish#holiday@group.v.calendar.google.com"
           - "en.taiwan#holiday@group.v.calendar.google.com"
           - "en.uk#holiday@group.v.calendar.google.com"
           - "en.usa#holiday@group.v.calendar.google.com"
           - "en.vietnamese#holiday@group.v.calendar.google.com"
      holidayLoadRange: 2592000000
      runFrequency: 1
    mockEventsLoader: true
    mockEventsLoaderConfiguration:
      generators:
        - type: HOLIDAY
          arrivalType: exponential
          arrivalMean: 86400000
          durationType: fixed
          durationMean: 86400000
          seed: 0
          namePrefixes: [First, Second, Third, Last, Funky, Happy, Sad, Glorious, Jolly, Unity, Pinot's]
          nameSuffixes: [day, day, days, celebration, rememberance, occurrence, moment]
        - type: INFORMED
          arrivalType: exponential
          arrivalMean: 43200000
          durationType: exponential
          durationMean: 3600000
          seed: 1
          namePrefixes: [Login, Web, Search, Catalog, Integration, Network, Backup, Ingress, Proxy, Failure, Pinot, ThirdEye]
          nameSuffixes: [backend, frontend, v1.1, v1.2, v1.3, v2.0, v3, v4, v5, storage, topic, container, database]
        - type: CM
          arrivalType: exponential
          arrivalMean: 21600000
          durationType: fixed
          durationMean: 1800000
          seed: 2
          namePrefixes: [Database, Web, Search, Catalog, Integration, Network, Backup, Ingress, Proxy, Failure, Pinot, ThirdEye]
        - type: CUSTOM
          arrivalType: exponential
          arrivalMean: 432000000
          durationType: exponential
          durationMean: 86400000
          seed: 3
          namePrefixes: [Marketing, Onboarding, Vaction, Outreach, InDay]
          nameSuffixes: [integration, campaign, meeting]
        - type: LIX
          arrivalType: exponential
          arrivalMean: 259200000
          durationType: exponential
          durationMean: 604800000
          seed: 4
          namePrefixes: [System, Model, Campaign, Welcome, Pinot, ThirdEye]

  data-sources-config.yml: |-
    # Please put the mock data source as the first in this configuration.
    dataSourceConfigs:
      - className: org.apache.pinot.thirdeye.datasource.pinot.PinotThirdEyeDataSource
        properties:
          zookeeperUrl: 'pinot-zookeeper:2181'
          clusterName: 'pinot-quickstart'
          controllerConnectionScheme: 'http'
          controllerHost: 'pinot-controller'
          controllerPort: 9000
          cacheLoaderClassName: org.apache.pinot.thirdeye.datasource.pinot.PinotControllerResponseCacheLoader
        metadataSourceConfigs:
          - className: org.apache.pinot.thirdeye.auto.onboard.AutoOnboardPinotMetadataSource

  cache-config.yml: |-
    useInMemoryCache: true
    useCentralizedCache: false

    centralizedCacheSettings:
      # TTL (time-to-live) for documents in seconds
      ttl: 3600
      # if inserting data points individually, max number of threads to spawn to parallel insert at a time
      maxParallelInserts: 10
      # which store to use
      cacheDataStoreName: 'couchbase'
      cacheDataSources:
        couchbase:
          className: org.apache.pinot.thirdeye.detection.cache.CouchbaseCacheDAO
          config:
            useCertificateBasedAuthentication: false
            # at least 1 host needed
            hosts:
              - 'host1' # ex. http://localhost:8091
              - 'host2' # ex. http://localhost:8092
              - 'host3' # ex. http://localhost:8093
              - 'host4' # and so on...
            bucketName: 'your_bucket_name'
            # if using certificate-based authentication, authUsername and authPassword values don't matter and won't be used
            authUsername: 'your_bucket_user_username'
            authPassword: 'your_bucket_user_password'
            enableDnsSrv: false
            # certificate based authentication is only available in Couchbase enterprise edition.
            keyStoreFilePath: 'key/store/path/keystore_file' # e.g. '/var/identity.p12'
            # if your keystore has a password, enter it here. by default, Java uses 'work_around_jdk-6879539' to enable empty passwords for certificates.
            keyStorePassword: 'work_around_jdk-6879539'
            trustStoreFilePath: 'trust/store/path/truststore_file' # e.g. '/etc/riddler/cacerts'
            trustStorePassword: ''
        # add your store of choice here
