version: '3'

services:
#  pinot_thirdeye:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      image: pinot_thirdeye
#      container_name: pinot_thirdeye
#      expose:
#        - "1426"
#        - "1427"
#      ports:
#        - 1426:1426
#        - 1427:1427
#      networks:
#        - default
  dashboard:
    image: utkarshsaxena/pinot_thirdeye:latest
    environment:
      - CLASSPATH="org.apache.pinot.thirdeye.anomaly.ThirdEyeDashboardApplication"
    ports:
      - "1426:1426"
      - "1427:1427"
    #entrypoint: java -cp "/opt/thirdeye/bin/thirdeye-pinot-1.0.0-SNAPSHOT.jar" org.apache.pinot.thirdeye.anomaly.ThirdEyeDashboardApplication "/opt/thirdeye/config"
  backend:
    image: utkarshsaxena/pinot_thirdeye:latest
    environment:
      - CLASSPATH="org.apache.pinot.thirdeye.anomaly.ThirdEyeAnomalyApplication"
    ports:
      - "1428:1426"
      - "1429:1427"
    #entrypoint: java -cp "/opt/thirdeye/bin/thirdeye-pinot-1.0.0-SNAPSHOT.jar" org.apache.pinot.thirdeye.anomaly.ThirdEyeAnomalyApplication "/opt/thirdeye/config"
  thirdeye_postgres:
    image: postgres:9.6
    container_name: thirdeye_postgres
    ports:
      - 25432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=thirdeye
    networks:
      - default